[build]
  # kein Build nötig, es ist eine statische Seite
  command = ""
  publish = "site"
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/assets/**"]

[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "no-store, must-revalidate"
