[build]
  command = "echo 'Static site - no build needed'"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  port = 8888
  publish = "."
  framework = "#static"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
